# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipelineMarc-conn'
    subscriptionId: '33a5bac4-dea9-40d2-8250-2a5ee8a9e670'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipelineMarc-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Tjoep1975/AzureRmPipelineMarc-repo/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureRm'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
